 cmake_minimum_required(VERSION 3.20) 
 project(KerbalSpace LANGUAGES CXX) 
 set(CMAKE_CXX_STANDARD 26) 
 set(CMAKE_CXX_STANDARD_REQUIRED ON) 
 add_executable(kerbal cpp/main.cpp cpp/deltaV.cpp ) 
 target_include_directories(kerbal PRIVATE header) 
 target_link_libraries(kerbal PRIVATE stdc++exp) 
 if(WIN32)
    target_link_options(kerbal PRIVATE "-static-libgcc" "-static-libstdc++" "-static")
    endif()